# -*- coding: utf-8 -*-
"""Plant Disease Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krxdIUQZyLgnpVxteePkRdBA9DJ0g0HT
"""

!pip install tensorflow-datasets

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
from tensorflow.keras.applications import ResNet50
from google.colab import files
from IPython.display import Image, display
import cv2
from PIL import Image as PILImage
import io

# Load the PlantVillage dataset from TFDS
# This will download the dataset (~1.2GB) if not already cached
dataset_name = 'plant_village'
(ds_train, ds_test), ds_info = tfds.load(
    dataset_name,
    split=['train[:80%]', 'train[80%:]'],  # Use 80-20 split
    as_supervised=True,
    with_info=True
)

# Get class names
class_names = ds_info.features['label'].names
num_classes = len(class_names)
print(f"Number of classes: {num_classes}")
print("Sample classes:", class_names[:5])

# ResNet50 expects images of size 224x224 and normalized to [0,1]
IMG_SIZE = 224

def preprocess_image(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0  # Normalize to [0,1]
    return image, label

# Apply preprocessing
ds_train = ds_train.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
ds_test = ds_test.map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)

BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

# Shuffle, batch, prefetch
ds_train = ds_train.shuffle(1000).batch(BATCH_SIZE).prefetch(AUTOTUNE)
ds_test = ds_test.batch(BATCH_SIZE).prefetch(AUTOTUNE)

# Optional: Display a batch
for images, labels in ds_train.take(1):
    print("Image batch shape:", images.shape)
    print("Label batch shape:", labels.shape)

# Load pre-trained ResNet50 without top layers
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(IMG_SIZE, IMG_SIZE, 3))

# Freeze base model layers initially
base_model.trainable = False

# Add custom classification head
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(num_classes, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Early stopping to prevent overfitting
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

EPOCHS = 2  # Increase for better accuracy, but 5 is enough for demo

history = model.fit(
    ds_train,
    validation_data=ds_test,
    epochs=EPOCHS,
    callbacks=[early_stop]
)

# Plot training & validation accuracy and loss
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(len(acc))

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

def predict_uploaded_image(model, class_names):
    uploaded = files.upload()
    for filename in uploaded.keys():
        # Display the uploaded image
        display(Image(filename=filename, width=300))

        # Load and preprocess the image
        img = PILImage.open(io.BytesIO(uploaded[filename])).convert('RGB')
        img = img.resize((IMG_SIZE, IMG_SIZE))
        img_array = np.array(img) / 255.0
        img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

        # Predict
        predictions = model.predict(img_array)
        predicted_class = np.argmax(predictions[0])
        confidence = np.max(predictions[0])

        print(f"Predicted Disease: {class_names[predicted_class]}")
        print(f"Confidence: {confidence:.2f}")

# Take one image from test set and predict
for image, label in ds_test.unbatch().take(1):
    img_array = np.expand_dims(image.numpy(), axis=0)
    pred = model.predict(img_array)
    pred_class = np.argmax(pred[0])
    true_class = label.numpy()
    print(f"True: {class_names[true_class]}, Predicted: {class_names[pred_class]}")

# Run this cell and upload a plant leaf image
predict_uploaded_image(model, class_names)











